# Notebook to extract nodes corresponding to network motifs from a GRN (and mFinder results)

- Last updated: 9/28/2023
- Author: Yang-Joon Kim

- inputs: a GRN (CellOracle Links object), and a mFinder result (network motifs, a txt file)
- outputs(TBD): a dataframe of nodes, edges for corresponding motifs

- Tentative df-  columns: index_triplet, source_node, target_node, edge width, motif_name

In [1]:
# Import libraries
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import seaborn as sns

import celloracle as co
co.__version__

from itertools import combinations

/home/yang-joon.kim/.conda/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:68: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def twobit_to_dna(twobit: int, size: int) -> str:
/home/yang-joon.kim/.conda/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:85: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def dna_to_twobit(dna: str) -> int:
/home/yang-joon.kim/.conda/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:102: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def twobit_1hamming(twobit: int, size: int) -> List[int]:
INFO:matplotlib.font_manager:Failed to extract font properties from /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf: In FT2Font: Can not load face (unknown file format; error code 0x2)

'0.14.0'

In [4]:
# plotting module
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault) #Reset rcParams to default

# Editable text and proper LaTeX fonts in illustrator
# matplotlib.rcParams['ps.useafm'] = True
# Editable fonts. 42 is the magic number
mpl.rcParams['pdf.fonttype'] = 42
sns.set(style='whitegrid', context='paper')

# Plotting style function (run this before plotting the final figure)
def set_plotting_style():
    plt.style.use('seaborn-paper')
    plt.rc('axes', labelsize=12)
    plt.rc('axes', titlesize=12)
    plt.rc('xtick', labelsize=10)
    plt.rc('ytick', labelsize=10)
    plt.rc('legend', fontsize=10)
    plt.rc('text.latex', preamble=r'\usepackage{sfmath}')
    plt.rc('xtick.major', pad=2)
    plt.rc('ytick.major', pad=2)
    plt.rc('mathtext', fontset='stixsans', sf='sansserif')
    plt.rc('figure', figsize=[10,9])
    plt.rc('svg', fonttype='none')

set_plotting_style()

In [166]:
# import a custom function to process the mFinder OUTPUT file (txt)
sys.path.append("/hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/zebrahub-multiome-analysis/scripts/")
from extract_motifs_mFinder_output import extract_motifs_mFinder_output

In [164]:
help(extract_motifs_mFinder_output)

Help on function extract_motifs_mFinder_output in module extract_motifs_mFinder_output:

extract_motifs_mFinder_output(mFinder_output)

In [172]:
mFinder_output = "/hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/data/processed_data/baseGRN_CisBP_RNA_zebrahub/09_network_motifs/motifs_0budstage_Somites_OUT.txt"
df_motifs = extract_motifs_mFinder_output(mFinder_output)
df_motifs

MOTIF	NREAL	NRAND		NREAL	NREAL	UNIQ	CREAL
ID		STATS		ZSCORE	PVAL	VAL	[MILI]

46	675	401.4+-19.6	13.99	0.000	9	13.73

0 1 1
1 0 1
0 0 0

108	100	64.2+-8.6	4.15	0.000	8	2.03

0 0 1
1 0 1
1 0 0

238	16	6.1+-2.3	4.30	0.000	4	0.33

0 1 1
1 0 1
1 1 0

,MOTIF_ID,NREAL,NRAND_STATS,NREAL_ZSCORE,NREAL_PVAL,UNIQ_VAL,CREAL_[MILI],motifs
0,46,675,401.4+-19.6,13.99,0.000,9,13.73,"[[0, 1, 1], [1, 0, 1], [0, 0, 0]]"
1,108,100,64.2+-8.6,4.15,0.000,8,2.03,"[[0, 0, 1], [1, 0, 1], [1, 0, 0]]"
2,238,16,6.1+-2.3,4.30,0.000,4,0.33,"[[0, 1, 1], [1, 0, 1], [1, 1, 0]]"

## load the GRN

In [148]:
filepath_GRN = "/hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/data/processed_data/baseGRN_CisBP_RNA_zebrahub/08_0budstage_celltype_GRNs.celloracle.links"
GRN = co.load_hdf5(filepath_GRN)

In [151]:
celltype = "Somites"
GRN_celltype = GRN.filtered_links[celltype]
GRN_celltype

        source   target  coef_mean  coef_abs             p      -logp
358430   foxd2      ved  -0.201453  0.201453  8.021183e-16  15.095762
197037  dmrt2a   mespab   0.198571  0.198571  1.016912e-16  15.992717
196815  hoxc6b   mespaa   0.196897  0.196897  7.465155e-17  16.126961
332389  dmrt2a     tbx6   0.190522  0.190522  5.323086e-15  14.273836
196758  hoxb3a    meox1   0.186918  0.186918  1.006142e-12  11.997341
...        ...      ...        ...       ...           ...        ...
87037    barx1      dlc   0.037743  0.037743  5.479247e-11  10.261279
285163   alx4a  sema3aa   0.037727  0.037727  8.268290e-13  12.082584
22938    tbx16     aspm   0.037720  0.037720  1.547360e-16  15.810409
154452  nr2f1a   hoxb3a   0.037703  0.037703  2.981958e-06   5.525498
156270   six1b   hoxc6b  -0.037702  0.037702  1.789292e-13  12.747319

[2000 rows x 6 columns]

In [155]:
source_nodes = set(GRN_celltype.source)
target_nodes = set(GRN_celltype.target)

In [159]:
gene_nodes = source_nodes|target_nodes 
len(gene_nodes)

331

In [167]:
print(len(source_nodes))
print(len(target_nodes))
print(len(source_nodes & target_nodes))
print(len(source_nodes | target_nodes))

167
215
51
331

In [ ]:

for node1 in gene_nodes:
    for node2 in gene_nodes:
        for node3 in gene_nodes:

In [169]:
GRN_celltype

        source   target  coef_mean  coef_abs             p      -logp
358430   foxd2      ved  -0.201453  0.201453  8.021183e-16  15.095762
197037  dmrt2a   mespab   0.198571  0.198571  1.016912e-16  15.992717
196815  hoxc6b   mespaa   0.196897  0.196897  7.465155e-17  16.126961
332389  dmrt2a     tbx6   0.190522  0.190522  5.323086e-15  14.273836
196758  hoxb3a    meox1   0.186918  0.186918  1.006142e-12  11.997341
...        ...      ...        ...       ...           ...        ...
87037    barx1      dlc   0.037743  0.037743  5.479247e-11  10.261279
285163   alx4a  sema3aa   0.037727  0.037727  8.268290e-13  12.082584
22938    tbx16     aspm   0.037720  0.037720  1.547360e-16  15.810409
154452  nr2f1a   hoxb3a   0.037703  0.037703  2.981958e-06   5.525498
156270   six1b   hoxc6b  -0.037702  0.037702  1.789292e-13  12.747319

[2000 rows x 6 columns]

In [196]:
df_motifs

,MOTIF_ID,NREAL,NRAND_STATS,NREAL_ZSCORE,NREAL_PVAL,UNIQ_VAL,CREAL_[MILI],motifs
0,46,675,401.4+-19.6,13.99,0.000,9,13.73,"[[0, 1, 1], [1, 0, 1], [0, 0, 0]]"
1,108,100,64.2+-8.6,4.15,0.000,8,2.03,"[[0, 0, 1], [1, 0, 1], [1, 0, 0]]"
2,238,16,6.1+-2.3,4.30,0.000,4,0.33,"[[0, 1, 1], [1, 0, 1], [1, 1, 0]]"

In [186]:
df_motifs['motifs']

0    [[0, 1, 1], [1, 0, 1], [0, 0, 0]]
1    [[0, 0, 1], [1, 0, 1], [1, 0, 0]]
2    [[0, 1, 1], [1, 0, 1], [1, 1, 0]]
Name: motifs, dtype: object

In [174]:
motifs = set(tuple(row) for row in df_motifs[['MOTIF_ID', 'motifs']].values)

TypeError: unhashable type: 'numpy.ndarray'

In [194]:
# From ChatGPT

# Load your GRN dataframe
# df = pd.read_csv("path_to_your_GRN.csv")  # replace with your file path
df = GRN_celltype

# Convert the dataframe into a set of directed edges for easy querying
edges = set(tuple(row) for row in df[['source', 'target']].values)


#df_motifs[['MOTIF_ID', 'motifs']]

# Define your motifs
motif_matrices = [
    [[0, 1, 1], [1, 0, 1], [0, 0, 0]],
    [[0, 0, 1], [1, 0, 1], [1, 0, 0]],
    [[0, 1, 1], [1, 0, 1], [1, 1, 0]]
]

# Function to get adjacency matrix for a triplet from the GRN
def get_adjacency_matrix(triplet, edges):
    matrix = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            if (triplet[i], triplet[j]) in edges:
                matrix[i][j] = 1
    return matrix.tolist()

# # Check each triplet in the GRN against the motifs
# instances = {}
# for idx, motif in enumerate(motif_matrices):
#     instances[idx] = []

#     for triplet in combinations(df['source'].unique(), 3):
#         matrix = get_adjacency_matrix(triplet, edges)
#         if matrix == motif:
#             instances[idx].append(triplet)

# Union of unique 'source' and 'target' nodes
all_unique_nodes = set(df['source'].unique()).union(set(df['target'].unique()))

# Check each triplet in the GRN against the motifs
instances = {}
for idx, motif in enumerate(motif_matrices):
    instances[idx] = []

    for triplet in combinations(all_unique_nodes, 3):
        matrix = get_adjacency_matrix(triplet, edges)
        if matrix == motif:
            instances[idx].append(triplet)

# Convert instances into a dataframe
rows = []
for idx, instance_list in instances.items():
    for instance in instance_list:
        rows.append({'MOTIF_ID': idx, 'INSTANCE': instance})

instances_df = pd.DataFrame(rows)

print(instances_df)

     MOTIF_ID                    INSTANCE
0           0  (sox11b, hoxb3a, gadd45ba)
1           0      (raraa, hoxb6b, sulf1)
2           0    (raraa, hoxb6b, ripply2)
3           0      (raraa, hoxb6b, msgn1)
4           0      (raraa, hoxb6b, tob1a)
..        ...                         ...
325         2       (lbx2, meox1, hoxc6b)
326         2       (lbx2, meox1, hoxb3a)
327         2      (lbx2, hoxc6b, hoxc3a)
328         2    (hoxc6b, hoxb7a, hoxb9a)
329         2     (hoxa9a, hoxb10a, vent)

[330 rows x 2 columns]

In [197]:
df_motifs

,MOTIF_ID,NREAL,NRAND_STATS,NREAL_ZSCORE,NREAL_PVAL,UNIQ_VAL,CREAL_[MILI],motifs
0,46,675,401.4+-19.6,13.99,0.000,9,13.73,"[[0, 1, 1], [1, 0, 1], [0, 0, 0]]"
1,108,100,64.2+-8.6,4.15,0.000,8,2.03,"[[0, 0, 1], [1, 0, 1], [1, 0, 0]]"
2,238,16,6.1+-2.3,4.30,0.000,4,0.33,"[[0, 1, 1], [1, 0, 1], [1, 1, 0]]"

In [199]:
dict_motif_id = {0:"46",
                 1:"108",
                 2:"238"}

instances_df.MOTIF_ID = instances_df.MOTIF_ID.map(dict_motif_id)
instances_df

    MOTIF_ID                    INSTANCE
0         46  (sox11b, hoxb3a, gadd45ba)
1         46      (raraa, hoxb6b, sulf1)
2         46    (raraa, hoxb6b, ripply2)
3         46      (raraa, hoxb6b, msgn1)
4         46      (raraa, hoxb6b, tob1a)
..       ...                         ...
325      238       (lbx2, meox1, hoxc6b)
326      238       (lbx2, meox1, hoxb3a)
327      238      (lbx2, hoxc6b, hoxc3a)
328      238    (hoxc6b, hoxb7a, hoxb9a)
329      238     (hoxa9a, hoxb10a, vent)

[330 rows x 2 columns]

In [193]:
instances_df.value_counts("MOTIF_ID")

MOTIF_ID
1    43
0    26
2    16
dtype: int64

In [203]:
instances_df.to_csv("/hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/data/processed_data/baseGRN_CisBP_RNA_zebrahub/10_extracted_nodes_motifs/motifs_node_genes_0budstage_Somites.csv")

In [190]:
GRN_celltype[GRN_celltype.source.isin(["hoxc6b"])]

        source   target  coef_mean  coef_abs             p      -logp
196815  hoxc6b   mespaa   0.196897  0.196897  7.465155e-17  16.126961
196962  hoxc6b   mespab   0.146066  0.146066  1.072631e-13  12.969550
113871  hoxc6b     fn1a   0.140702  0.140702  2.977078e-17  16.526210
156109  hoxc6b   hoxc3a   0.109417  0.109417  1.386627e-17  16.858040
8743    hoxc6b  aldh1a2   0.105079  0.105079  8.696644e-15  14.060648
...        ...      ...        ...       ...           ...        ...
147163  hoxc6b     her2   0.042444  0.042444  8.353280e-13  12.078143
150082  hoxc6b     hhip   0.041315  0.041315  2.799864e-14  13.552863
154883  hoxc6b   hoxb6b   0.041053  0.041053  3.281597e-12  11.483915
196329  hoxc6b   meis2a  -0.040498  0.040498  2.947274e-18  17.530579
146976  hoxc6b  her15.2   0.038201  0.038201  7.426601e-11  10.129210

[62 rows x 6 columns]

In [192]:
# Check the 3-size subgraph to make sure that we're detecting real motifs
GRN_celltype[GRN_celltype.source.isin(["hoxc6b","meox1","foxc1a"]) & GRN_celltype.target.isin(["hoxc6b","meox1","foxc1a"])]

        source  target  coef_mean  coef_abs             p      -logp
115685   meox1  foxc1a   0.111256  0.111256  1.320519e-16  15.879255
196659  hoxc6b   meox1   0.072215  0.072215  3.578723e-10   9.446272
115594  hoxc6b  foxc1a   0.055481  0.055481  1.162409e-09   8.934641
156420   meox1  hoxc6b   0.039263  0.039263  1.769696e-10   9.752101

In [207]:
GRN_celltype[GRN_celltype.source.isin(["hoxc6b"])]

        source   target  coef_mean  coef_abs             p      -logp
196815  hoxc6b   mespaa   0.196897  0.196897  7.465155e-17  16.126961
196962  hoxc6b   mespab   0.146066  0.146066  1.072631e-13  12.969550
113871  hoxc6b     fn1a   0.140702  0.140702  2.977078e-17  16.526210
156109  hoxc6b   hoxc3a   0.109417  0.109417  1.386627e-17  16.858040
8743    hoxc6b  aldh1a2   0.105079  0.105079  8.696644e-15  14.060648
...        ...      ...        ...       ...           ...        ...
147163  hoxc6b     her2   0.042444  0.042444  8.353280e-13  12.078143
150082  hoxc6b     hhip   0.041315  0.041315  2.799864e-14  13.552863
154883  hoxc6b   hoxb6b   0.041053  0.041053  3.281597e-12  11.483915
196329  hoxc6b   meis2a  -0.040498  0.040498  2.947274e-18  17.530579
146976  hoxc6b  her15.2   0.038201  0.038201  7.426601e-11  10.129210

[62 rows x 6 columns]

In [209]:
GRN_celltype[GRN_celltype.target.isin(["meox1"])]

          source target  coef_mean  coef_abs             p      -logp
196758    hoxb3a  meox1   0.186918  0.186918  1.006142e-12  11.997341
196702      lbx2  meox1   0.144452  0.144452  2.983676e-12  11.525248
196777      drgx  meox1   0.115880  0.115880  2.510371e-10   9.600262
196623      hmx2  meox1  -0.109058  0.109058  2.439399e-10   9.612717
196625    hoxb1b  meox1   0.105862  0.105862  6.388394e-13  12.194608
196683      en1b  meox1  -0.103473  0.103473  5.404167e-10   9.267271
196730   uncx4.1  meox1   0.095479  0.095479  2.561343e-13  12.591532
196718       ved  meox1  -0.091832  0.091832  4.190964e-18  17.377686
196738      vent  meox1  -0.087787  0.087787  3.023177e-15  14.519536
196736   phox2bb  meox1   0.085253  0.085253  6.737022e-12  11.171532
196656     hmx3a  meox1  -0.074318  0.074318  1.117063e-12  11.951922
196688      sox7  meox1   0.073103  0.073103  8.706823e-10   9.060140
196659    hoxc6b  meox1   0.072215  0.072215  3.578723e-10   9.446272
196761    prrx1b  meox1  -0.065584  0.065584  2.851991e-09   8.544852
196696     tbx15  meox1   0.062333  0.062333  7.356270e-11  10.133342
196670      en1a  meox1   0.061881  0.061881  7.228722e-08   7.140938
196750  nkx1.2lb  meox1  -0.060982  0.060982  3.836686e-08   7.416044
196747      alx1  meox1  -0.060951  0.060951  4.198691e-09   8.376886
196739     foxp4  meox1   0.060025  0.060025  1.570424e-11  10.803983
196743      uncx  meox1   0.059010  0.059010  6.127123e-10   9.212743
196776    hoxb8a  meox1   0.058553  0.058553  8.808648e-06   5.055091
196653     alx4a  meox1   0.057560  0.057560  1.237646e-10   9.907403
196752     tbx18  meox1   0.057524  0.057524  3.333741e-10   9.477068
196655      en2b  meox1   0.057086  0.057086  2.096443e-11  10.678517
196658     tbx2a  meox1  -0.056307  0.056307  9.366662e-09   8.028415
196722       vox  meox1  -0.053803  0.053803  3.298504e-13  12.481683
196729      isl1  meox1   0.051136  0.051136  6.345064e-11  10.197564
196677    nkx2.7  meox1  -0.050946  0.050946  4.518075e-11  10.345047
196694     tbx5a  meox1  -0.049204  0.049204  1.012262e-04   3.994707
196707      etv1  meox1   0.047526  0.047526  4.710973e-08   7.326889
196668     egr2a  meox1  -0.046779  0.046779  9.215576e-10   9.035478
196674    hoxa9b  meox1  -0.044166  0.044166  2.756259e-15  14.559680
196705     lhx2a  meox1   0.043975  0.043975  9.946158e-08   7.002345
196626    hoxd4a  meox1  -0.043812  0.043812  1.068668e-17  16.971157
196717     lhx1a  meox1  -0.043499  0.043499  3.452314e-10   9.461890
196686     mixl1  meox1  -0.041453  0.041453  2.116838e-08   7.674312
196721     pax7b  meox1   0.040830  0.040830  9.852488e-06   5.006454
196753      etv2  meox1   0.040768  0.040768  1.715046e-06   5.765724
196671     sox17  meox1   0.040255  0.040255  2.084649e-09   8.680967
196637     fli1a  meox1  -0.040093  0.040093  6.050209e-09   8.218230
196748      lhx6  meox1   0.040025  0.040025  1.152201e-04   3.938472
196639      emx2  meox1   0.039328  0.039328  1.123954e-08   7.949251
196641    hoxc8a  meox1  -0.038323  0.038323  3.228812e-12  11.490957

In [218]:
sns.scatterplot(GRN_celltype[GRN_celltype.target.isin(["meox1"])].coef_mean)
plt.show

In [212]:
plt.scatter(GRN_celltype[GRN_celltype.target.isin(["meox1"])].coef_mean, 
            GRN_celltype[GRN_celltype.target.isin(["meox1"])].p)
plt.show()